
version: '3'

services:
  egh-cache:
    image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
    container_name: egh-cache
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6379:6379"
    networks:
      - eghnet
    volumes:
      - redis_data:/data

  egh-mono:
    image: eghacr.azurecr.io/egh-mono:latest
    container_name: egh-mono
    build: .
    command:
      - --store=redis
      - --redis=egh-cache:6379
      - --gw=:8080
    ports:
      - "8080:8080"
    links:
      - egh-cache
    depends_on:
      - egh-cache
    networks:
      - eghnet
    env_file: .egh-api.env

volumes:
  redis_data:
    external: false

secrets:
  egh-api-env:
    file: .egh-api.env

networks:
  eghnet:
