
version: '3'
services:
  redis:
    image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
    container_name: egh-cache
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
        - "6379:6379"
    volumes:
      - redis_data:/data

  egh-back:
    image: eghacr.azurecr.io/egh-api:latest
    container_name: egh-back
    build: ./egh-api
    ports:
        - "8080:8080"

  egh-front:
    image: eghacr.azurecr.io/egh-front:latest
    container_name: egh-front
    build: ./discover-frontend
    ports:
        - "5173:5173"

volumes:
  redis_data:
    external: false
